### PR TITLE
Fix #107: Cursor is reset to position 0

### LINKED ISSUE #107: Specifying options inline does not work properly
When trying to specify a param inline, the input does not accept a `space` character after the URL.  Note below the lack of space between `/api/something` and `page==2`.  The cursor also resets to position 0 in this situation.

output

The command actually works, but the command line processing is not handled properly.

### PR DESCRIPTION
**Pull request by eliangcs**

### CODE REVIEW

**Comment by eliangcs** [comment]
@fogine just a small fix. Would you like to review?

**Comment by fogine** [comment]
@eliangcs the fix works, however, in this case I don't understand why the cursor position was being reset to 0 and how not including escaped characters `(\\.)` in matched result solves the issue.
Can you explain, please?

**Comment by eliangcs** [comment]
At [line 159](https://github.com/eliangcs/http-prompt/blob/48b9afa9/http_prompt/lexer.py#L159), `bygroups(String, Text)`, we only has two groups, but the original regex `r'([^\-](?:[^\s"\'\\=:]|(\\.))+)(\s+|$)'` captures three groups:

* `([^\-](?:[^\s"\'\\=:]|(?:\\.))+)`
* `(\\.)`
* `(\s+|$)`

`(\\.)` was captured by mistake. The fix adds a `?:` to exclude it from being captured.

@fogine does it make sense?

**Comment by fogine** [comment]
yeah, that makes quite sense. I haven't noticed we use only two groups. That caused the `pygments` trying to  render incorrect group as the `Text`... probably causing unwanted characters being written to the stdout which led to cursor reset... roughly explained.

Thanks @eliangcs

**Pull request merged**
