### PR TITLE
Enable persistent history support.

### PR DESCRIPTION
**Pull request by lonetwin**

### CODE REVIEW

**Comment by lonetwin** [comment]
Please let me know whether this seems reasonable, if yes, I'll add some test and resubmit sometime soon.

**Comment by eliangcs** [comment]
@lonetwin persistent history is something I always want to do. Thanks!

Instead of making it configurable, can we just replace InMemoryHistory with FileHistory. And we can hard-code the file location to $XDG_DATA_HOME/http-prompt/history. Just like we did for [persistent context](http://docs.http-prompt.com/en/latest/user-guide.html#persistent-context).

**Comment by lonetwin** [comment]
I've made the changes you recommended. That's indeed a good default approach.

Unfortunately, I haven't been able to add a test quickly enough (can't honestly, without having to spend more time). I'll aim to do it sometime but it'd be great if you consider this change trivial enough to accept the PR without one for now.

**Comment by eliangcs** [comment]
Yes, I agree this is a simple change to leave the test out. Thank you for your contribution! 👍

**Pull request merged**
