### PR TITLE
Add Dockerfile for building docker container

### PR DESCRIPTION
**Pull request by frosforever**
Not sure if this is something appropriate in the repo, but I'm a fan of leveraging docker for running tools.

To build:
```
docker build -t http-prompt .
```
and to run:
```
docker run -it --rm http-prompt
```

If this is appropriate, next steps would be setting up an automated build on docker/hub that would build on every merge etc. I've done that already for my fork here https://hub.docker.com/r/frosforever/http-prompt/. The image can be pulled down and run via:
```
docker run -it --rm frosforever/http-prompt
```

See https://docs.docker.com/docker-hub/builds/ for the steps required to set up an automated build.

### CODE REVIEW

**Comment by eliangcs** [comment]
I don't think Dockerfile belongs to this repo for the following reasons:

1. HTTP Prompt is a just simple and lightweight tool, which can be installed with a simple `pip install` command. No server required, so there's really no need to run it in Docker.

2. I prefer deployment configuration should be put to its own repo and http-prompt is included as a dependency.

**Comment by jgelens** [comment]
@frosforever isn't that overkill? :] Maybe this project is interesting for you? https://github.com/mitsuhiko/pipsi

**Comment by sjourdan** [comment]
My use case is to use http-prompt precisely on environments where neither python nor pip are installed, like CoreOS machines, etc. 

My Dockerfile approach is a little different on this repo: https://github.com/sjourdan/http-prompt-docker
And you'll find the versioned containers here: https://hub.docker.com/r/sjourdan/http-prompt/

Thanks for your work!

**Comment by eliangcs** [comment]
@sjourdan thank you for providing an alternative way to install http-prompt as well! Closing this PR.

**Comment by frosforever** [comment]
@jgelens "one mans overkill is another's... something something something" 😄 

@eliangcs Thanks for considering!

**Pull request closed without merging**
