### PR TITLE
Fix exception in Windows 

### PR DESCRIPTION
**Pull request by Yegorov**

### CODE REVIEW

**Comment by eliangcs** [comment]
This PR makes output coloring gone on Mac OS. Maybe you should disable the `stdout_isatty` option only when it's on Windows.

**Comment by Yegorov** [comment]
Why not use the standard output in this code (execution.py,  line 240):
``` python
#output = BytesIO()
import sys
output = sys.stdout
try:
    env = Environment(stdout=output)
    httpie_main(context.httpie_args(self.method), env=env)
    #content = output.getvalue()
finally:
    pass
    #output.close()

# XXX: Work around a bug of click.echo_via_pager(). When you pass
# a bytestring to echo_via_pager(), it converts the bytestring with
# str(b'abc'), which makes it "b'abc'".
#if six.PY2:
#    content = unicode(content, 'utf-8')
#else:
#    content = str(content, 'utf-8')
#click.echo_via_pager(content)
```

This work in Windows and colored terminal.
img

But if you do not change the existing code, need option is_windows:
``` python
env = Environment(stdout=output, is_windows=False)
```
This also works in Windows but not colored terminal.

**Comment by eliangcs** [comment]
`click.echo_via_page()` doesn't accept a stream object. We need to store the output to a string so that we can use `click.echo_via_page()` to paginate the output.

**Comment by Yegorov** [comment]
If use is_windows=False option on Mac OS is work ok?
In Windows it needs to be fixed, in current version (0.2.0) not working any requests.

**Comment by eliangcs** [comment]
I finally have a chance to test it on Windows. `is_windows=False` works on Mac OS, but it disables output coloring on Windows. I'll find some time to have a full test on Windows. Thanks!

**Comment by Yegorov** [comment]
> but it disables output coloring on Windows.
In Windows impossible to get color not in sys.stdout stream. See [this](https://github.com/jkbrzt/httpie/blob/master/tests/test_windows.py#L31)
Option is_windows=False is a solution this problem.

**Comment by eliangcs** [comment]
I see. Do you mind sending another patch for `is_windows=False`? I'll merge it.

**Comment by Yegorov** [comment]
Ok

**Pull request closed without merging**
